"""Live (production) diagnostic tools — execute real commands against actual infrastructure."""

from diagnostics.tools.live.gpu import check_gpu_health, check_gpu_memory, check_gpu_utilization
from diagnostics.tools.live.hosts import (
    check_cpu,
    check_disk,
    check_memory,
    check_network,
    check_processes,
    get_system_overview,
    list_diagnostic_capabilities,
)
from diagnostics.tools.live.kubernetes import (
    check_certificate_expiry,
    check_etcd_health,
    check_rbac_permissions,
    check_service_endpoints,
    check_webhook_status,
    describe_coredns,
    describe_controller,
    describe_pod,
    explain_resource,
    get_api_resources,
    get_api_versions,
    get_cluster_events,
    get_cluster_overview,
    get_configmap,
    get_coredns_logs,
    get_etcd_logs,
    get_etcd_metrics,
    get_etcd_status,
    get_helm_release_history,
    get_helm_release_values,
    get_ingress_status,
    get_namespaces,
    get_network_policies,
    get_node_conditions,
    get_node_info,
    get_node_resource_usage,
    get_pod_events,
    get_pod_logs,
    get_pod_logs_lines,
    get_pod_logs_since,
    get_pod_previous_logs,
    get_pod_resource_usage,
    get_pod_restart_counts,
    get_pv_pvc_status,
    get_resource_yaml,
    get_system_pods,
    list_clusters,
    list_helm_releases,
    list_namespace_resources,
)

__all__ = [
    # Host-level
    "get_system_overview",
    "check_cpu",
    "check_memory",
    "check_disk",
    "check_network",
    "check_processes",
    "list_diagnostic_capabilities",
    # GPU
    "check_gpu_health",
    "check_gpu_memory",
    "check_gpu_utilization",
    # Kubernetes
    "list_clusters",
    "get_namespaces",
    "get_cluster_overview",
    "get_pod_logs",
    "get_pod_logs_since",
    "get_pod_logs_lines",
    "get_pod_previous_logs",
    "describe_pod",
    "get_pod_events",
    "get_cluster_events",
    "get_node_info",
    "get_node_conditions",
    "get_pod_resource_usage",
    "get_node_resource_usage",
    "get_system_pods",
    "get_coredns_logs",
    "describe_coredns",
    "list_helm_releases",
    "get_helm_release_history",
    "get_helm_release_values",
    "get_network_policies",
    "check_rbac_permissions",
    "get_pod_restart_counts",
    "check_certificate_expiry",
    "check_webhook_status",
    "get_etcd_status",
    "get_etcd_logs",
    "check_etcd_health",
    "get_etcd_metrics",
    "check_service_endpoints",
    "get_configmap",
    "list_namespace_resources",
    "get_pv_pvc_status",
    "get_ingress_status",
    "describe_controller",
    "explain_resource",
    "get_api_resources",
    "get_api_versions",
    "get_resource_yaml",
]
