"""Tool registry — production (live) surface, signatures mirror mock."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from diagnostics.tools.live.argus import (
    get_argus_k8s_cluster_metrics,
    get_argus_k8s_master_metrics,
    get_argus_k8s_node_metrics,
    get_argus_k8s_pod_metrics,
    get_argus_k8s_workload_metrics,
    get_argus_os_cpu_metrics,
    get_argus_os_disk_metrics,
    get_argus_os_kernel_metrics,
    get_argus_os_load_metrics,
    get_argus_os_mem_metrics,
    get_argus_os_nas_metrics,
    get_argus_os_net_metrics,
    get_argus_os_ntp_metrics,
    get_argus_os_overview_metrics,
    get_argus_os_ping_metrics,
    get_argus_os_tcp_metrics,
    get_argus_shared_etcd_metrics,
)

from diagnostics.tools.live.gpu import (
    get_gpu_dmesg_info,
    get_gpu_driver_info,
    get_gpu_mod_info,
    get_gpu_pcie_info,
    get_gpu_status_info,
)

from diagnostics.tools.live.hosts import (
    get_os_base_info,
    get_os_block_5s,
    get_os_block_info,
    get_os_cpu_cs,
    get_os_cpu_info,
    get_os_cpu_load,
    get_os_cpu_ps_elf,
    get_os_kernel_dmesg_err,
    get_os_kernel_journalctl_period,
    get_os_kernel_numa_info,
    get_os_kernel_sysctl_all,
    get_os_kernel_sysctl_grep,
    get_os_kernel_sysctl_one,
    get_os_mem_5s,
    get_os_mem_oom,
    get_os_mem_top_process,
    get_os_net_conntrack,
    get_os_net_ethtool,
    get_os_net_ethtools_s,
    get_os_net_nslookup,
    get_os_net_ping,
    get_os_net_sar_dev,
    get_os_net_softirqs,
    get_os_net_softnet_stat,
    get_os_net_ss_s,
    get_os_net_tc_stat,
    get_os_system_overview,
)

from diagnostics.tools.live.kubernetes import (
    check_k8s_certificate_expiry,
    check_k8s_control_plane,
    check_k8s_etcd_health,
    check_k8s_nodes,
    check_k8s_pods,
    check_k8s_rbac_permissions,
    check_k8s_service_endpoints,
    check_k8s_webhook_status,
    describe_k8s_controller,
    describe_k8s_coredns,
    describe_k8s_resource,
    explain_k8s_resource,
    get_k8s_api_resources,
    get_k8s_api_versions,
    get_k8s_apigateway_status,
    get_k8s_cluster_events,
    get_k8s_cluster_overview,
    get_k8s_configmap,
    get_k8s_coredns_logs,
    get_k8s_elb_service,
    get_k8s_etcd_check,
    get_k8s_etcd_logs,
    get_k8s_etcd_metrics,
    get_k8s_etcd_status,
    get_k8s_group1_status,
    get_k8s_helm_release_history,
    get_k8s_helm_release_values,
    get_k8s_ingress_status,
    get_k8s_ipam_status,
    get_k8s_kubelet_logs,
    get_k8s_kubelet_status,
    get_k8s_kubeproxy_logs,
    get_k8s_namespaces,
    get_k8s_network_policies,
    get_k8s_node_conditions,
    get_k8s_node_events_info,
    get_k8s_node_info,
    get_k8s_node_resource_usage,
    get_k8s_pod_events_info,
    get_k8s_pod_ip,
    get_k8s_pod_logs,
    get_k8s_pod_logs_head,
    get_k8s_pod_logs_since,
    get_k8s_pod_previous_logs,
    get_k8s_pod_resource_usage,
    get_k8s_pod_restart_counts,
    get_k8s_pv_pvc_status,
    get_k8s_resource_history,
    get_k8s_resource_list,
    get_k8s_resource_summary,
    get_k8s_resource_top,
    get_k8s_resource_yaml,
    get_k8s_system_pods,
    get_k8s_vpc_cni,
    get_k8s_xid_logs,
    get_pod_node_name,
    list_k8s_helm_releases,
    list_k8s_namespace_resources,
)



def get_agent_tools(extra_tools: Sequence[Any] = ()) -> list[Any]:
    """Coordinator tools in production mode — delegation-only (no diagnostics)."""
    return [*extra_tools]

def get_k8s_live_tools() -> list[Any]:
    """k8s-expert surface: actual-environment 36-tool set + 18 project-only tools."""
    return [
        get_pod_node_name,
        get_k8s_kubelet_status,
        get_k8s_kubelet_logs,
        get_k8s_etcd_check,
        get_k8s_kubeproxy_logs,
        get_k8s_xid_logs,
        get_k8s_node_info,
        get_k8s_node_events_info,
        get_k8s_pod_events_info,
        get_k8s_pod_logs,
        get_k8s_cluster_overview,
        get_k8s_namespaces,
        get_k8s_pod_logs_since,
        get_k8s_pod_logs_head,
        get_k8s_pod_previous_logs,
        get_k8s_cluster_events,
        get_k8s_pod_resource_usage,
        get_k8s_node_resource_usage,
        get_k8s_api_resources,
        get_k8s_api_versions,
        get_k8s_resource_yaml,
        get_k8s_system_pods,
        describe_k8s_controller,
        check_k8s_service_endpoints,
        get_k8s_configmap,
        list_k8s_namespace_resources,
        get_k8s_pv_pvc_status,
        get_k8s_ingress_status,
        explain_k8s_resource,
        get_k8s_elb_service,
        get_k8s_vpc_cni,
        get_k8s_resource_top,
        get_k8s_resource_list,
        get_k8s_resource_summary,
        get_k8s_resource_history,
        describe_k8s_resource,
        get_k8s_coredns_logs,
        describe_k8s_coredns,
        list_k8s_helm_releases,
        get_k8s_helm_release_history,
        get_k8s_helm_release_values,
        get_k8s_etcd_status,
        get_k8s_etcd_logs,
        check_k8s_etcd_health,
        get_k8s_etcd_metrics,
        get_k8s_network_policies,
        check_k8s_rbac_permissions,
        get_k8s_pod_restart_counts,
        get_k8s_node_conditions,
        check_k8s_certificate_expiry,
        check_k8s_webhook_status,
        check_k8s_pods,
        check_k8s_nodes,
        check_k8s_control_plane,
    ]

def get_k8s_family_live_tools() -> list[Any]:
    """serverless/kmc/sci deep experts: k8s-expert surface + 4 family supplements."""
    return [
        get_pod_node_name,
        get_k8s_kubelet_status,
        get_k8s_kubelet_logs,
        get_k8s_etcd_check,
        get_k8s_kubeproxy_logs,
        get_k8s_xid_logs,
        get_k8s_node_info,
        get_k8s_node_events_info,
        get_k8s_pod_events_info,
        get_k8s_pod_logs,
        get_k8s_cluster_overview,
        get_k8s_namespaces,
        get_k8s_pod_logs_since,
        get_k8s_pod_logs_head,
        get_k8s_pod_previous_logs,
        get_k8s_cluster_events,
        get_k8s_pod_resource_usage,
        get_k8s_node_resource_usage,
        get_k8s_api_resources,
        get_k8s_api_versions,
        get_k8s_resource_yaml,
        get_k8s_system_pods,
        describe_k8s_controller,
        check_k8s_service_endpoints,
        get_k8s_configmap,
        list_k8s_namespace_resources,
        get_k8s_pv_pvc_status,
        get_k8s_ingress_status,
        explain_k8s_resource,
        get_k8s_elb_service,
        get_k8s_vpc_cni,
        get_k8s_resource_top,
        get_k8s_resource_list,
        get_k8s_resource_summary,
        get_k8s_resource_history,
        describe_k8s_resource,
        get_k8s_coredns_logs,
        describe_k8s_coredns,
        list_k8s_helm_releases,
        get_k8s_helm_release_history,
        get_k8s_helm_release_values,
        get_k8s_etcd_status,
        get_k8s_etcd_logs,
        check_k8s_etcd_health,
        get_k8s_etcd_metrics,
        get_k8s_network_policies,
        check_k8s_rbac_permissions,
        get_k8s_pod_restart_counts,
        get_k8s_node_conditions,
        check_k8s_certificate_expiry,
        check_k8s_webhook_status,
        check_k8s_pods,
        check_k8s_nodes,
        check_k8s_control_plane,
        get_k8s_apigateway_status,
        get_k8s_group1_status,
        get_k8s_ipam_status,
        get_k8s_pod_ip,
    ]

def get_host_argus_live_tools() -> list[Any]:
    """host-argus-expert: 11 get_argus_os_*_metrics."""
    return [
        get_argus_os_overview_metrics,
        get_argus_os_cpu_metrics,
        get_argus_os_mem_metrics,
        get_argus_os_disk_metrics,
        get_argus_os_net_metrics,
        get_argus_os_nas_metrics,
        get_argus_os_ping_metrics,
        get_argus_os_tcp_metrics,
        get_argus_os_kernel_metrics,
        get_argus_os_load_metrics,
        get_argus_os_ntp_metrics,
    ]

def get_k8s_argus_live_tools() -> list[Any]:
    """k8s-argus-expert: 5 canonical dimension tools."""
    return [
        get_argus_k8s_cluster_metrics,
        get_argus_k8s_node_metrics,
        get_argus_k8s_workload_metrics,
        get_argus_k8s_pod_metrics,
        get_argus_k8s_master_metrics,
    ]

def get_family_argus_live_tools() -> list[Any]:
    """Family argus experts: 5 canonical + shared etcd."""
    return [
        get_argus_k8s_cluster_metrics,
        get_argus_k8s_node_metrics,
        get_argus_k8s_workload_metrics,
        get_argus_k8s_pod_metrics,
        get_argus_k8s_master_metrics,
        get_argus_shared_etcd_metrics,
    ]

def get_host_live_tools() -> list[Any]:
    """host-expert: get_os_* family (27)."""
    return [
        get_os_base_info,
        get_os_system_overview,
        get_os_kernel_sysctl_one,
        get_os_kernel_sysctl_all,
        get_os_kernel_sysctl_grep,
        get_os_kernel_dmesg_err,
        get_os_kernel_numa_info,
        get_os_mem_5s,
        get_os_mem_top_process,
        get_os_mem_oom,
        get_os_cpu_info,
        get_os_net_ethtools_s,
        get_os_net_softnet_stat,
        get_os_net_tc_stat,
        get_os_net_sar_dev,
        get_os_net_softirqs,
        get_os_net_conntrack,
        get_os_block_info,
        get_os_block_5s,
        get_os_cpu_load,
        get_os_cpu_cs,
        get_os_net_ss_s,
        get_os_kernel_journalctl_period,
        get_os_cpu_ps_elf,
        get_os_net_ethtool,
        get_os_net_ping,
        get_os_net_nslookup,
    ]

def get_gpu_live_tools() -> list[Any]:
    """host-expert GPU part: get_gpu_* family (5)."""
    return [
        get_gpu_pcie_info,
        get_gpu_driver_info,
        get_gpu_mod_info,
        get_gpu_status_info,
        get_gpu_dmesg_info,
    ]
